#!/bin/bash
set -e

# CDISC Cache Setup Script
# This script automates the setup of Varnish cache with API key injection

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "======================================"
echo "CDISC Cache Setup Script"
echo "======================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Error: This script must be run as root${NC}"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    echo -e "${RED}Error: Cannot detect OS${NC}"
    exit 1
fi

echo -e "${GREEN}Detected OS: $OS${NC}"
echo ""

# Function to read API key securely
read_api_key() {
    echo -e "${YELLOW}Please enter your CDISC API key:${NC}"
    read -s CDISC_API_KEY
    echo ""
    
    if [ -z "$CDISC_API_KEY" ]; then
        echo -e "${RED}Error: API key cannot be empty${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}API key received (hidden)${NC}"
}

# Install Varnish
install_varnish() {
    echo "Installing Varnish..."
    
    case $OS in
        ubuntu|debian)
            apt-get update
            apt-get install -y varnish
            ;;
        rhel|centos|fedora)
            yum install -y varnish
            ;;
        alpine)
            apk add --no-cache varnish
            ;;
        *)
            echo -e "${RED}Unsupported OS: $OS${NC}"
            exit 1
            ;;
    esac
    
    echo -e "${GREEN}Varnish installed${NC}"
}

# Setup Varnish configuration
setup_varnish() {
    echo "Setting up Varnish configuration..."
    
    # Create directories
    mkdir -p /etc/varnish
    mkdir -p /var/lib/varnish
    
    # Copy VCL files (assumes they're in current directory)
    if [ ! -f "default.vcl" ]; then
        echo -e "${RED}Error: default.vcl not found in current directory${NC}"
        exit 1
    fi
    
    cp default.vcl /etc/varnish/default.vcl
    chmod 644 /etc/varnish/default.vcl
    
    # Create API key configuration
    cat > /etc/varnish/api_key.vcl << EOF
# CDISC API Key Configuration
# Generated by setup script

C{
    const char *CDISC_API_KEY = "$CDISC_API_KEY";
}C
EOF
    
    # Secure the API key file
    chmod 600 /etc/varnish/api_key.vcl
    chown root:varnish /etc/varnish/api_key.vcl 2>/dev/null || chown root:root /etc/varnish/api_key.vcl
    
    echo -e "${GREEN}Varnish configuration completed${NC}"
}

# Configure persistent storage
configure_storage() {
    echo "Configuring persistent storage..."
    
    case $OS in
        ubuntu|debian|rhel|centos|fedora)
            # Systemd-based systems
            if [ -f /etc/varnish/varnish.params ]; then
                sed -i 's/^VARNISH_STORAGE=.*/VARNISH_STORAGE="persistent,\/var\/lib\/varnish\/storage.bin,50G"/' /etc/varnish/varnish.params
            else
                echo 'VARNISH_STORAGE="persistent,/var/lib/varnish/storage.bin,50G"' > /etc/varnish/varnish.params
            fi
            ;;
        alpine)
            # OpenRC-based system
            cat > /etc/conf.d/varnishd << EOF
VARNISHD_OPTS="-s persistent,/var/lib/varnish/storage.bin,50G \\
               -a :6081 \\
               -T localhost:6082 \\
               -f /etc/varnish/default.vcl \\
               -p feature=+http2"
EOF
            ;;
    esac
    
    echo -e "${GREEN}Storage configuration completed${NC}"
}

# Start Varnish service
start_varnish() {
    echo "Starting Varnish..."
    
    case $OS in
        ubuntu|debian|rhel|centos|fedora)
            systemctl daemon-reload
            systemctl enable varnish
            systemctl restart varnish
            systemctl status varnish --no-pager
            ;;
        alpine)
            rc-update add varnishd default
            rc-service varnishd restart
            rc-service varnishd status
            ;;
    esac
    
    echo -e "${GREEN}Varnish started${NC}"
}

# Verify installation
verify_installation() {
    echo ""
    echo "Verifying installation..."
    
    # Wait for Varnish to start
    sleep 2
    
    # Test basic connectivity
    if curl -s -o /dev/null -w "%{http_code}" http://localhost:6081/api/mdr/products | grep -q "200\|301\|302"; then
        echo -e "${GREEN}✓ Varnish is responding${NC}"
    else
        echo -e "${YELLOW}⚠ Warning: Varnish might not be responding correctly${NC}"
    fi
    
    # Check if API key is hidden
    if curl -I http://localhost:6081/api/mdr/products 2>/dev/null | grep -qi "api-key"; then
        echo -e "${RED}✗ SECURITY WARNING: API key is being exposed!${NC}"
    else
        echo -e "${GREEN}✓ API key is properly hidden${NC}"
    fi
    
    # Check cache headers
    if curl -I http://localhost:6081/api/mdr/products 2>/dev/null | grep -q "X-Cache"; then
        echo -e "${GREEN}✓ Cache headers are present${NC}"
    else
        echo -e "${YELLOW}⚠ Warning: Cache headers not found${NC}"
    fi
}

# Main execution
main() {
    read_api_key
    install_varnish
    setup_varnish
    configure_storage
    start_varnish
    verify_installation
    
    echo ""
    echo "======================================"
    echo -e "${GREEN}Setup completed successfully!${NC}"
    echo "======================================"
    echo ""
    echo "Next steps:"
    echo "1. Install and configure the Rust invalidator"
    echo "2. Test the cache: curl -I http://localhost:6081/api/mdr/products"
    echo "3. Monitor logs: journalctl -u varnish -f"
    echo ""
    echo -e "${YELLOW}IMPORTANT: Keep /etc/varnish/api_key.vcl secure!${NC}"
}

main